# docker-compose.yml

version: '3.8'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  meetup:
    build:
      context: .
      dockerfile: ./apps/meetup/Dockerfile
    command: npm run start:dev meetup
    env_file:
      - ./apps/meetup/.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - meetup
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meetup_micro_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
  
 
